kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "directus.fullname" . }}-batch-jobs
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
